"""
LexIntellectus - Case Management Models
Expedientes, Partes Procesales, and Case Metadata.
Based on data_model.md v2.0, Section 2.1 - 2.2
"""

import uuid
from datetime import datetime, date
from sqlalchemy import (
    Column, String, Text, Boolean, Integer, Date, DateTime,
    ForeignKey, Enum, Numeric
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from app.core.database import Base


class EstadoExpediente(Base):
    """Case Status configuration (e.g. Activo, Suspendido, Cerrado)."""
    __tablename__ = "case_statuses"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id = Column(UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False)
    codigo = Column(String(50), nullable=False)
    nombre = Column(String(100), nullable=False)
    color_hex = Column(String(7))
    es_final = Column(Boolean, default=False)
    orden = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    expedientes = relationship("Expediente", back_populates="estado")


class Expediente(Base):
    """Legal Case / Expediente Judicial."""
    __tablename__ = "cases"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id = Column(UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False)
    sede_id = Column(UUID(as_uuid=True), ForeignKey("branches.id"), nullable=True)
    numero_interno = Column(String(50), nullable=True) # Generated by system
    numero_causa = Column(String(100), nullable=True) # Judicial number
    
    # === TIPO DE SERVICIO LEGAL ===
    tipo_servicio = Column(
        Enum(
            'litigio',                # Caso judicial (comportamiento clásico)
            'escritura',              # Protocolo notarial
            'asesoria',               # Asesoría / retainer continuo
            'tramite',                # Trámite administrativo / registral
            'consulta',               # Consulta puntual / opinión legal
            'mediacion',              # Mediación / arbitraje
            'contrato',               # Administración de contratos
            'due_diligence',          # Auditoría legal / DD
            'propiedad_intelectual',  # Marcas, patentes, derechos de autor
            'gestion_corporativa',    # Mantenimiento societario
            name="service_type"
        ),
        nullable=False,
        default='litigio'
    )

    # Classification (aplica principalmente a litigios)
    ramo = Column(
        Enum(
            'civil', 'penal', 'familia', 'laboral', 'mercantil', 
            'constitucional', 'sucesiones', 'administrativo',
            name="case_branch"
        ),
        nullable=True  # Ya no es obligatorio: escrituras/asesorías pueden no tener ramo
    )
    materia_especifica = Column(String(100)) # e.g. Divorcio, Cobro
    
    # Court Info
    juzgado = Column(String(255))
    juez = Column(String(200))
    secretario = Column(String(200))
    
    # State & Workflows
    estado_id = Column(UUID(as_uuid=True), ForeignKey("case_statuses.id"), nullable=True)
    etapa_actual_id = Column(UUID(as_uuid=True), ForeignKey("workflow_stages.id"), nullable=True)
    tipo_proceso = Column(String(100))  # ordinario, ejecutivo, monitorio, divorcio_contencioso...
    
    # Details
    resumen = Column(Text)
    fecha_apertura = Column(Date, default=date.today)
    fecha_cierre = Column(Date)
    
    # Responsibility
    abogado_responsable_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    cliente_principal_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    co_abogados = Column(JSONB, default=[])  # [user_ids] — equipo de apoyo
    abogado_contraparte = Column(String(255))  # Nombre del abogado de contraparte
    
    prioridad = Column(
        Enum('baja', 'normal', 'alta', 'urgente', name="case_priority"),
        default='normal'
    )
    valor_estimado = Column(Numeric(15, 2))
    moneda = Column(String(3), default="NIO")
    observaciones_ia = Column(Text)
    
    # === RESULTADO / RESOLUCIÓN (cuando cierra el caso) ===
    tipo_resolucion = Column(String(100))  # sentencia_favorable, conciliacion, desistimiento...
    numero_sentencia = Column(String(100))
    fecha_sentencia = Column(Date)
    resultado_detalle = Column(Text)
    monto_adjudicado = Column(Numeric(15, 2))
    recurso_pendiente = Column(Boolean, default=False)
    
    # === CAMPOS ESPECÍFICOS POR MATERIA (JSONB flexible) ===
    datos_materia = Column(JSONB, default={})
    # Penal: {delito_imputado, medida_cautelar_vigente, fiscal_asignado}
    # Familia: {pension_provisional, menores_involucrados, tipo_divorcio}
    # Laboral: {salario_base, fecha_inicio_laboral, fecha_despido, causa_despido}
    # Notarial: {numero_escritura, tomo_protocolo, folio_protocolo, tipo_acto}
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    estado = relationship("EstadoExpediente", back_populates="expedientes")
    etapa_actual = relationship("EtapaProcesal", foreign_keys=[etapa_actual_id])
    abogado_responsable = relationship("Usuario", foreign_keys=[abogado_responsable_id])
    cliente_principal = relationship("Usuario", foreign_keys=[cliente_principal_id])
    partes = relationship("ParteProcesal", back_populates="expediente", cascade="all, delete-orphan")
    plazos = relationship("PlazoFatal", back_populates="expediente", cascade="all, delete-orphan")


class ParteProcesal(Base):
    """Case Participants / Sujetos Procesales."""
    __tablename__ = "case_parties"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    expediente_id = Column(UUID(as_uuid=True), ForeignKey("cases.id"), nullable=False)
    
    nombre_completo = Column(String(255), nullable=False)
    tipo_persona = Column(Enum('natural', 'juridica', name="person_type"), default='natural')
    
    documento_identidad = Column(String(50))
    tipo_documento = Column(
        Enum('cedula', 'pasaporte', 'ruc', 'otro', name="doc_type"),
        default='cedula'
    )
    
    rol_procesal = Column(
        Enum(
            # === LITIGIO ===
            'demandante', 'demandado', 'tercero_interesado',
            'tercero_excluyente', 'ministerio_publico', 'procuraduria',
            'testigo', 'perito', 'abogado_contraparte',
            # === NOTARIAL ===
            'otorgante', 'adquiriente', 'compareciente',
            'testigo_instrumental', 'interprete',
            # === CONTRATOS / MEDIACIÓN ===
            'parte_a', 'parte_b', 'mediador', 'arbitro', 'garante',
            # === TRÁMITES ===
            'solicitante', 'beneficiario', 'gestor',
            # === CORPORATIVO ===
            'sociedad', 'socio_fundador', 'representante',
            # === UNIVERSAL ===
            'cliente', 'contraparte', 'otro',
            name="procedural_role"
        ),
        nullable=False
    )
    
    representante_legal = Column(String(255))
    abogado_patrocinador = Column(String(255))
    direccion = Column(Text)
    telefono = Column(String(20))
    email = Column(String(255))
    notas = Column(Text)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    expediente = relationship("Expediente", back_populates="partes")


class PlazoFatal(Base):
    """Legal Deadlines / Plazos Fatales."""
    __tablename__ = "deadlines"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    expediente_id = Column(UUID(as_uuid=True), ForeignKey("cases.id"), nullable=False)
    
    descripcion = Column(String(255), nullable=False)
    tipo_plazo = Column(
        Enum(
            'procesal', 'contractual', 'administrativo',
            'registral', 'notarial', 'institucional',
            name="deadline_type"
        ),
        default='procesal'
    )
    fecha_inicio = Column(Date)
    fecha_vencimiento = Column(Date, nullable=False)
    hora_vencimiento = Column(String(8), default="23:59:59") # simple string for time or Time type
    dias_tipo = Column(Enum('habiles', 'calendario', name="days_type"), default='habiles')
    
    base_legal = Column(String(100))
    usuario_responsable_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    
    status = Column(
        Enum('pendiente', 'cumplido', 'vencido', 'cancelado', name="deadline_status"),
        default='pendiente'
    )
    prioridad = Column(Enum('normal', 'alta', 'critica', name="deadline_priority"), default='normal')
    
    # Alerts
    alerta_72h_enviada = Column(Boolean, default=False)
    alerta_24h_enviada = Column(Boolean, default=False)
    alerta_1h_enviada = Column(Boolean, default=False)
    
    acciones_sugeridas_ia = Column(Text)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    expediente = relationship("Expediente", back_populates="plazos")
    usuario_responsable = relationship("Usuario")
