"""API v1 module init."""
from .health import *
from .auth import *
from .users import *
from .tenants import *
from .cases import *
from .deadlines import *
from .documents import *
from .notifications import *
from .dashboard import *
