"""Add case extended models

Revision ID: 1e4072f5b552
Revises: ed976c1b40b2
Create Date: 2026-03-08 20:17:03.064272
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e4072f5b552'
down_revision: Union[str, None] = 'ed976c1b40b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('ramo', sa.Enum('civil', 'penal', 'familia', 'laboral', 'mercantil', 'constitucional', 'sucesiones', 'administrativo', 'notarial', name='workflow_branch'), nullable=False),
    sa.Column('tipo_proceso', sa.String(length=100), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('dias_plazo_legal', sa.Integer(), nullable=True),
    sa.Column('tipo_dias', sa.Enum('habiles', 'calendario', name='stage_days_type'), nullable=True),
    sa.Column('base_legal', sa.String(length=200), nullable=True),
    sa.Column('es_final', sa.Boolean(), nullable=True),
    sa.Column('acciones_requeridas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plantillas_sugeridas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=True),
    sa.Column('datos_antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datos_despues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expediente_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('estrategia', 'investigacion', 'recordatorio', 'reunion_cliente', 'reunion_equipo', 'observacion', 'contraargumento', 'jurisprudencia', name='note_type'), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('es_privada', sa.Boolean(), nullable=True),
    sa.Column('prioridad', sa.Enum('normal', 'importante', 'urgente', name='note_priority'), nullable=True),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expediente_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expediente_id', sa.UUID(), nullable=False),
    sa.Column('estado_anterior_id', sa.UUID(), nullable=True),
    sa.Column('estado_nuevo_id', sa.UUID(), nullable=False),
    sa.Column('etapa_procesal_id', sa.UUID(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('registrado_por_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estado_anterior_id'], ['case_statuses.id'], ),
    sa.ForeignKeyConstraint(['estado_nuevo_id'], ['case_statuses.id'], ),
    sa.ForeignKeyConstraint(['etapa_procesal_id'], ['workflow_stages.id'], ),
    sa.ForeignKeyConstraint(['expediente_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_theories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expediente_id', sa.UUID(), nullable=False),
    sa.Column('hechos_relevantes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pretensiones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normas_aplicables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excepciones_previstas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pruebas_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fortalezas', sa.Text(), nullable=True),
    sa.Column('debilidades', sa.Text(), nullable=True),
    sa.Column('riesgos', sa.Text(), nullable=True),
    sa.Column('estrategia_general', sa.Text(), nullable=True),
    sa.Column('contraargumentos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generada_por_ia', sa.Boolean(), nullable=True),
    sa.Column('analisis_ia', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('autor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expediente_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expediente_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('escrito_presentado', 'escrito_contraparte', 'providencia', 'auto', 'sentencia', 'audiencia', 'notificacion_judicial', 'recurso_interpuesto', 'recurso_contraparte', 'incidente', 'excepcion', 'medida_cautelar', 'diligencia', 'prueba_admitida', 'prueba_evacuada', 'acuerdo', 'peritaje', 'nota_interna', 'otro', name='event_type'), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_evento', sa.DateTime(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('etapa_procesal_id', sa.UUID(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('base_legal', sa.String(length=200), nullable=True),
    sa.Column('documento_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plazo_generado_id', sa.UUID(), nullable=True),
    sa.Column('registrado_por_id', sa.UUID(), nullable=True),
    sa.Column('asignado_a_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'completado', 'vencido', 'cancelado', name='event_status'), nullable=True),
    sa.Column('analisis_ia', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['etapa_procesal_id'], ['workflow_stages.id'], ),
    sa.ForeignKeyConstraint(['expediente_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['plazo_generado_id'], ['deadlines.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cases', sa.Column('etapa_actual_id', sa.UUID(), nullable=True))
    op.add_column('cases', sa.Column('tipo_proceso', sa.String(length=100), nullable=True))
    op.add_column('cases', sa.Column('co_abogados', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cases', sa.Column('abogado_contraparte', sa.String(length=255), nullable=True))
    op.add_column('cases', sa.Column('tipo_resolucion', sa.String(length=100), nullable=True))
    op.add_column('cases', sa.Column('numero_sentencia', sa.String(length=100), nullable=True))
    op.add_column('cases', sa.Column('fecha_sentencia', sa.Date(), nullable=True))
    op.add_column('cases', sa.Column('resultado_detalle', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('monto_adjudicado', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('cases', sa.Column('recurso_pendiente', sa.Boolean(), nullable=True))
    op.add_column('cases', sa.Column('datos_materia', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'cases', 'workflow_stages', ['etapa_actual_id'], ['id'])
    op.drop_column('cases', 'workflow_instance_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('workflow_instance_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'datos_materia')
    op.drop_column('cases', 'recurso_pendiente')
    op.drop_column('cases', 'monto_adjudicado')
    op.drop_column('cases', 'resultado_detalle')
    op.drop_column('cases', 'fecha_sentencia')
    op.drop_column('cases', 'numero_sentencia')
    op.drop_column('cases', 'tipo_resolucion')
    op.drop_column('cases', 'abogado_contraparte')
    op.drop_column('cases', 'co_abogados')
    op.drop_column('cases', 'tipo_proceso')
    op.drop_column('cases', 'etapa_actual_id')
    op.drop_table('case_events')
    op.drop_table('case_theories')
    op.drop_table('case_status_history')
    op.drop_table('case_notes')
    op.drop_table('audit_logs')
    op.drop_table('workflow_stages')
    # ### end Alembic commands ###
