"""add_deadlines

Revision ID: ad20b9cbd8cf
Revises: bdec5c173f6b
Create Date: 2026-02-15 19:40:23.367134
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad20b9cbd8cf'
down_revision: Union[str, None] = 'bdec5c173f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadlines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expediente_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('tipo_plazo', sa.Enum('procesal', 'contractual', 'administrativo', name='deadline_type'), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('hora_vencimiento', sa.String(length=8), nullable=True),
    sa.Column('dias_tipo', sa.Enum('habiles', 'calendario', name='days_type'), nullable=True),
    sa.Column('base_legal', sa.String(length=100), nullable=True),
    sa.Column('usuario_responsable_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pendiente', 'cumplido', 'vencido', 'cancelado', name='deadline_status'), nullable=True),
    sa.Column('prioridad', sa.Enum('normal', 'alta', 'critica', name='deadline_priority'), nullable=True),
    sa.Column('alerta_72h_enviada', sa.Boolean(), nullable=True),
    sa.Column('alerta_24h_enviada', sa.Boolean(), nullable=True),
    sa.Column('alerta_1h_enviada', sa.Boolean(), nullable=True),
    sa.Column('acciones_sugeridas_ia', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expediente_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['usuario_responsable_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deadlines')
    # ### end Alembic commands ###
