"""Add Legal AI Agent tables

Revision ID: ed976c1b40b2
Revises: ad20b9cbd8cf
Create Date: 2026-02-15 20:43:38.392986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ed976c1b40b2'
down_revision: Union[str, None] = 'ad20b9cbd8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('ley', 'decreto', 'jurisprudencia', 'doctrina', 'gaceta', name='ai_source_type'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('articulo_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('contenido_texto', sa.Text(), nullable=False),
    sa.Column('contenido_markdown', sa.Text(), nullable=True),
    sa.Column('vector_embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_count', sa.Integer(), nullable=True),
    sa.Column('hash_contenido', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_contenido')
    )
    op.create_table('laa_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('expediente_id', sa.UUID(), nullable=True),
    sa.Column('modo', sa.Enum('consultor', 'estratega', 'redactor', 'cartulario', name='ai_mode'), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('contexto_documentos_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('tokens_consumidos', sa.Integer(), nullable=True),
    sa.Column('costo_estimado_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.Enum('activa', 'cerrada', 'archivada', name='session_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expediente_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laa_case_theories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('expediente_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('resumen_ejecutivo', sa.Text(), nullable=True),
    sa.Column('hechos_facticos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fundamento_juridico_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pruebas_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fortalezas', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('debilidades', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('estrategia_recomendada', sa.Text(), nullable=True),
    sa.Column('proximos_pasos', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('confianza_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('aprobada_por', sa.UUID(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprobada_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expediente_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['laa_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laa_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.Enum('user', 'assistant', 'system', 'tool', name='message_role'), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('contenido_markdown', sa.Text(), nullable=True),
    sa.Column('attachments_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunks_utilizados_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('articulos_citados_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('jurisprudencia_citada_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('tokens_prompt', sa.Integer(), nullable=True),
    sa.Column('tokens_completion', sa.Integer(), nullable=True),
    sa.Column('modelo_usado', sa.String(length=50), nullable=True),
    sa.Column('latencia_ms', sa.Integer(), nullable=True),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['laa_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laa_notarial_validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.Column('resultado_global', sa.Enum('aprobado', 'con_advertencias', 'bloqueado', name='validation_result'), nullable=True),
    sa.Column('validaciones_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errores_count', sa.Integer(), nullable=True),
    sa.Column('advertencias_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['laa_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laa_notarial_validations')
    op.drop_table('laa_messages')
    op.drop_table('laa_case_theories')
    op.drop_table('laa_sessions')
    op.drop_table('legal_chunks')
    # ### end Alembic commands ###
